# Generated by Django 5.2.2 on 2025-06-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('academic_level', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('research_area', models.CharField(max_length=255)),
                ('contact_method', models.CharField(max_length=50)),
                ('services', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_ref', models.CharField(blank=True, default=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
