# Generated by Django 3.2.25 on 2025-06-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('academic_level', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('research_area', models.TextField()),
                ('contact_method', models.CharField(max_length=50)),
                ('services', models.JSONField()),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('payment_ref', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='FinalPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
                ('payment_proof', models.FileField(upload_to='final_payment_proofs/')),
                ('services', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
=======
>>>>>>> 3d0908f67f7c764f5057b0fddbb209d68a7e97e3
    ]
