# Generated by Django 5.2.2 on 2025-06-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
                ('payment_proof', models.FileField(upload_to='final_payment_proofs/')),
                ('services', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Final Payment Submission',
                'verbose_name_plural': 'Final Payment Submissions',
            },
        ),
    ]
