# Generated by Django 5.2.2 on 2025-06-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_finalpaymentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalpaymentsubmission',
            name='services',
        ),
    ]
